#!/usr/bin/env bash
# Displays DNS information for specified domain and subdomains

audit_domain() {
    local domain=$1
    local subdomain=$2
    
    check_subdomain() {
        local sub=$1
        local answer
        answer=$(dig "$sub.$domain" +short)
        
        if [ -z "$answer" ]; then
            echo "The subdomain $sub does not exist or has no A record"
        else
            echo "The subdomain $sub is a A record and points to $answer"
        fi
    }

    if [ -n "$subdomain" ]; then
        check_subdomain "$subdomain"
    else
        local subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            check_subdomain "$sub"
        done
    fi
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

audit_domain "$1" "$2"
